"""Deterministic fake LLM.

Routes on the ``TASK: <name>`` marker that every node places on the first line of
its system prompt, returning canned but structurally-valid output. This is the
single highest-value test fixture: it lets the full graph run — planning, SQL
generation, gold reasoning, retries — with zero network calls and stable output.
"""

from __future__ import annotations

import json
import re

from de_agent.services.llm.base import LLMResponse

_PLAN = json.dumps(
    {
        "layers": [
            {
                "layer": "bronze",
                "objective": "Ingest raw data as-is",
                "transformations": ["load from volume"],
                "target_table": "bronze_raw",
                "dq_rules": ["row_count > 0"],
            },
            {
                "layer": "silver",
                "objective": "Clean and conform",
                "transformations": ["cast types", "drop nulls on key", "dedupe"],
                "target_table": "silver_clean",
                "dq_rules": ["no null keys", "row_count > 0"],
            },
        ]
    }
)

_GOLD = json.dumps(
    {
        "facts": [
            {
                "name": "fact_orders",
                "grain": "one row per order line",
                "measures": ["amount", "quantity"],
                "dimension_keys": ["date_key", "customer_key"],
            }
        ],
        "dimensions": [
            {
                "name": "dim_customer",
                "grain": "one row per customer",
                "attributes": ["customer_id", "name"],
                "source_columns": ["cust_id", "name"],
            },
            {
                "name": "dim_date",
                "grain": "one row per day",
                "attributes": ["date_key", "year", "month"],
                "source_columns": ["order_ts"],
            },
        ],
        "suggested_kpis": ["total revenue", "orders per customer", "revenue by month"],
    }
)


class FakeLLMClient:
    def __init__(self, overrides: dict[str, str] | None = None) -> None:
        self._overrides = overrides or {}

    def complete(
        self,
        *,
        system: str,
        prompt: str,
        temperature: float = 0.0,
        max_tokens: int = 4096,
    ) -> LLMResponse:
        task = self._task_of(system)
        if task in self._overrides:
            return LLMResponse(text=self._overrides[task], model="fake")
        return LLMResponse(text=self._canned(task, prompt), model="fake")

    @staticmethod
    def _task_of(system: str) -> str:
        first = system.strip().splitlines()[0] if system.strip() else ""
        if first.upper().startswith("TASK:"):
            return first.split(":", 1)[1].strip()
        return "unknown"

    @classmethod
    def _canned(cls, task: str, prompt: str) -> str:
        if task == "planning":
            return _PLAN
        if task == "gold_reasoning":
            return _GOLD
        if task == "clarification":
            return json.dumps({"needs_clarification": False, "question": ""})
        if task in {"sql_generation", "error_correction"}:
            return cls._sql_for(prompt)
        if task == "documentation":
            return "# Pipeline documentation\n\nGenerated by the DE Agent."
        return "OK"

    @staticmethod
    def _sql_for(prompt: str) -> str:
        """Emit a CREATE statement for the *actual* target table named in the prompt.

        Keeps the fake realistic: the produced table matches what the node validates.
        """
        target_match = re.search(r"Target table \(fully qualified\):\s*(\S+)", prompt)
        source_match = re.search(r"Source table:\s*(\S+)", prompt)
        # error_correction prompts don't restate the target; recover it from the prior SQL.
        if not target_match:
            target_match = re.search(r"TABLE\s+([a-zA-Z0-9_.`]+)", prompt)
        target = target_match.group(1) if target_match else "cat.sch.target"
        source = source_match.group(1) if source_match else None
        select = f"SELECT * FROM {source}" if source and source != "None" else "SELECT 1 AS col"
        return f"```sql\nCREATE OR REPLACE TABLE {target} AS\n{select};\n```"
